docks:
  dock1:
    type: 'rosmaster_x3_dock'
    frame: map
    pose: [-10.0, -6.0, 1.5708]

  dock2:
    type: 'rosmaster_x3_dock'
    frame: map
    pose: [-14.0, -3.0, 0.0]

  dock3:
    type: 'rosmaster_x3_dock'
    frame: map
    pose: [-14.0, 0.0, 0.0]

  dock4:
    type: 'rosmaster_x3_dock'
    frame: map
    pose: [-10.0, 6.0, -1.5708]